[gcloud]
disabled = true

[battery]
disabled = false

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 30
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 90
style = "bold yellow"

[env_var]
variable = "STARSHIP_SHELL"

