#set -xe

export ADOTDIR=$HOME/.config/antigen
source "${ZDOTDIR:-$HOME}/.zsh/antigen.zsh"

zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:module:editor' key-bindings 'vi'
zstyle ':prezto:module:prompt' theme 'steeef'
zstyle ':prezto:module:python' autovenv 'yes'
zstyle ':prezto:load' pmodule \
  'environment' \
  'editor' \
  'history' \
  'git' \
  'prompt' \
  'python'

antigen use prezto

antigen bundle sorin-ionescu/prezto modules/environment
antigen bundle sorin-ionescu/prezto modules/editor
antigen bundle sorin-ionescu/prezto modules/history
antigen bundle sorin-ionescu/prezto modules/git
antigen bundle sorin-ionescu/prezto modules/prompt
antigen bundle sorin-ionescu/prezto modules/python
antigen bundle zsh-users/zsh-autosuggestions

antigen apply

source ~/.cargo/env

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GPG_TTY=$(tty)

# OPAM configuration
. /Users/pcaulagi/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# enable completions for docker, docker-compose
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i
source <(kubectl completion zsh)

# export PROJECT_ID=`gcloud config get-value project`
#export HOST_IP=`ifconfig en0 | grep inet | grep -v inet6 | cut -d ' ' -f2`
# for cases where we can't use docker.for.mac.localhost in containers
#
export CLOUDSDK_PYTHON=python2.7
export HOST_IP=192.168.65.2
export NNTPSERVER=nntp.aioe.org

export GOPATH=~/src/go
export PATH=$GOPATH/bin:$PATH
export PATH=$PATH:$HOME/.linkerd2/bin
export PATH=$PATH:~/bin
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# source ~/.zsh/completion/*
# source ~/.zsh/completion/aws_zsh_completer.sh
# source ~/.zsh/completion/_helm
# source ~/.zsh/completion/_kops

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export WEECHAT_HOME=~/.config/weechat

if type direnv > /dev/null; then
    eval "$(direnv hook zsh)"
fi

if [[ -d "$HOME/Downloads/google-cloud-sdk" ]]
then
    source "$HOME/Downloads/google-cloud-sdk/path.zsh.inc"
fi

if [[ -f "$HOME/.local/profile_zsh" ]]
then
    source "$HOME/.local/profile_zsh"
fi

if [[ -f "$HOME/.local/alias" ]]
then
    source "$HOME/.local/alias"
fi

[[ -f "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc" ]] && . "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc"

export NVM_DIR="$HOME"/.config/nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

if [[ -d "$HOME/Library/Android/sdk" ]]
then
    export ANDROID_HOME=$HOME/Library/Android/sdk
    export PATH=$PATH:$ANDROID_HOME/emulator
    export PATH=$PATH:$ANDROID_HOME/tools
    export PATH=$PATH:$ANDROID_HOME/tools/bin
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

if type zoxide > /dev/null; then
    eval "$(zoxide init zsh)"
fi
